/**
 * Created by Traven on 2017/1/22.
 */
export const SHOW_HEAD_ADV = 'SHOW_HEAD_ADV';
export const SHOW_NAV_VAL = 'SHOW_NAV_VAL';
export const SHOW_SEARCH_VAL = 'SHOW_SEARCH_VAL';
export const HIDE_NAV_AND_SEARCH = 'HIDE_NAV_AND_SEARCH';
export const SHOW_NAV_AND_SEARCH = 'SHOW_NAV_AND_SEARCH';
export const CHOOSE_MOVIE_TYPE_HOME = 'CHOOSE_MOVIE_TYPE_HOME';
export const HOME_MOVIE_DATA = 'HOME_MOVIE_DATA';
export const CINEMA_DATA = 'CINEMA_DATA';
export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const SAVE_NICK_NAME = 'SAVE_NICK_NAME';
export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SHOW_LOADING = 'SHOW_LOADING';

